### 查询指定商品的秒杀结果
GET http://localhost:8080/api/seckill/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidG9tIiwicGFzc3dvcmQiOiIxMjMiLCJraW5kIjowLCJhdWQiOiJ0b20iLCJleHAiOjE2MjM3NTI0NjIsImp0aSI6IjIiLCJpYXQiOjE2MjM3NDg4NjIsImlzcyI6InNlY29uZCBraWxsIiwibmJmIjoxNjIzNzQ4ODYyLCJzdWIiOiJhdXRoIn0.TnZezFP7tVExjVLi1mE_-HPwqA_t8V1-j2w39wN1kAo

### 秒杀指定商品
POST http://localhost:8080/api/seckill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidG9tIiwicGFzc3dvcmQiOiIxMjMiLCJraW5kIjowLCJhdWQiOiJ0b20iLCJleHAiOjE2MjM3NTI0NjIsImp0aSI6IjIiLCJpYXQiOjE2MjM3NDg4NjIsImlzcyI6InNlY29uZCBraWxsIiwibmJmIjoxNjIzNzQ4ODYyLCJzdWIiOiJhdXRoIn0.TnZezFP7tVExjVLi1mE_-HPwqA_t8V1-j2w39wN1kAo

{
  "goodsId": 1
}

###
