### 查询指定商品的秒杀结果
GET http://localhost:8080/api/seckill/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidG9tIiwicGFzc3dvcmQiOiIxMjMiLCJraW5kIjowLCJhdWQiOiJ0b20iLCJleHAiOjE2MjM1ODQwNjcsImp0aSI6IjIiLCJpYXQiOjE2MjM1ODA0NjcsImlzcyI6InNlY29uZCBraWxsIiwibmJmIjoxNjIzNTgwNDY3LCJzdWIiOiJhdXRoIn0.7LfhmfhdcJmJlCznhFallO114xIVp-0Er1FOX_JUxoU

### 秒杀指定商品
POST http://localhost:8080/api/seckill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidG9tIiwicGFzc3dvcmQiOiIxMjMiLCJraW5kIjowLCJhdWQiOiJ0b20iLCJleHAiOjE2MjM1ODQwNjcsImp0aSI6IjIiLCJpYXQiOjE2MjM1ODA0NjcsImlzcyI6InNlY29uZCBraWxsIiwibmJmIjoxNjIzNTgwNDY3LCJzdWIiOiJhdXRoIn0.7LfhmfhdcJmJlCznhFallO114xIVp-0Er1FOX_JUxoU

{
  "goodsId": 2
}

###
