definitions:
  model.LoginUser:
    properties:
      password:
        example: "123"
        type: string
      username:
        example: tom
        type: string
    required:
    - password
    - username
    type: object
  model.RegisterUser:
    properties:
      kind:
        example: 0
        type: integer
      password:
        example: "123"
        type: string
      username:
        example: tom
        type: string
    required:
    - password
    - username
    type: object
  model.Result:
    properties:
      code:
        example: 0
        type: integer
      data:
        type: object
      message:
        example: 响应信息
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录签发 JWT
      parameters:
      - description: 用户
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 用户登录
      tags:
      - 用户管理
  /api/user/logout:
    post:
      consumes:
      - application/json
      description: 用户退出登录，清除登录 token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 退出登录
      tags:
      - 用户管理
  /api/user/register:
    post:
      consumes:
      - application/json
      description: 注册用户并保存到数据库
      parameters:
      - description: 注册用户
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 用户注册
      tags:
      - 用户管理
swagger: "2.0"
