definitions:
  model.GoodsDTO:
    properties:
      amount:
        default: 0
        minimum: 1
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      endTime:
        type: string
      id:
        type: integer
      img:
        type: string
      name:
        type: string
      originPrice:
        default: 0
        minimum: 0
        type: number
      price:
        default: 0
        minimum: 0
        type: number
      startTime:
        type: string
      stock:
        default: 0
        minimum: 0
        type: integer
      updatedAt:
        type: string
    required:
    - amount
    - endTime
    - name
    - price
    - startTime
    - stock
    type: object
  model.LoginUser:
    properties:
      password:
        example: "123"
        type: string
      username:
        example: tom
        type: string
    required:
    - password
    - username
    type: object
  model.RegisterUser:
    properties:
      kind:
        example: 0
        type: integer
      password:
        example: "123"
        type: string
      username:
        example: tom
        type: string
    required:
    - password
    - username
    type: object
  model.Result:
    properties:
      code:
        example: 0
        type: integer
      data:
        type: object
      message:
        example: 响应信息
        type: string
    type: object
info:
  contact: {}
paths:
  /api/goods:
    post:
      consumes:
      - application/json
      description: 添加秒杀商品进秒杀系统
      parameters:
      - description: 秒杀商品传输信息
        in: body
        name: goods
        required: true
        schema:
          $ref: '#/definitions/model.GoodsDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 添加商品
      tags:
      - 商品管理
  /api/goods/{id}:
    get:
      consumes:
      - application/json
      description: 通过 id 查询秒杀商品
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 查询商品
      tags:
      - 商品管理
  /api/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录签发 JWT
      parameters:
      - description: 用户
        in: body
        name: loginUser
        required: true
        schema:
          $ref: '#/definitions/model.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 用户登录
      tags:
      - 用户管理
  /api/user/logout:
    post:
      consumes:
      - application/json
      description: 用户退出登录，清除登录 token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
      summary: 退出登录
      tags:
      - 用户管理
  /api/user/register:
    post:
      consumes:
      - application/json
      description: 注册用户并保存到数据库
      parameters:
      - description: 注册用户
        in: body
        name: registerUser
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Result'
      summary: 用户注册
      tags:
      - 用户管理
swagger: "2.0"
